export async function captureException(error: unknown) {
  console.error(error)
}
